
env_args:
    # env: 'TicTacToe'
    #env: 'Geister'
    #env: 'HungryGeese'
    #env: 'handyrl.envs.parallel_tictactoe'  # specify by path
    env: 'CIGeister'

train_args:
    turn_based_training: True
    observation: False
    gamma: 0.8
    forward_steps: 16
    compress_steps: 4
    entropy_regularization: 1.0e-1
    entropy_regularization_decay: 0.1
    update_episodes: 200
    batch_size: 256
    minimum_episodes: 400
    maximum_episodes: 100000
    epochs: -1
    num_batchers: 2
    eval_rate: 0.1
    worker:
        num_parallel: 6 # Number of processes
    lambda: 0.7
    policy_target: 'UPGO' # 'UPGO' 'VTRACE' 'TD' 'MC'
    value_target: 'VTRACE' # 'VTRACE' 'TD' 'MC'
    seed: 0
    restart_epoch: 0 # Specify when restarting learning from the middle (0 means start from the beginning)


worker_args:
    server_address: ''
    num_parallel: 8

